### ISSUE TITLE
 error: attribute 'android:name' in <provider> tag must be a valid Java class name. (IONIC 4)

### ISSUE THREAD

**Issue by sourabh0110** [Wiseonesoft/cordova-whatsapp-sticker-plugin#10]
Working on the issue since a long time now but still not able to resolve.

Please Note - Making a build on IONIC 4 

![image](https://user-images.githubusercontent.com/11188082/90327413-f112ca00-dfb0-11ea-9073-ffd1690acb6b.png)

**Comment by H4ad** [comment]
Maybe it is not related to this plugin because i don't add native code for Android, try to remove the plugin and run again `ionic build`.
