### ISSUE TITLE
Please, I tried but it didn't work, I ask for help

### ISSUE THREAD

**Issue by fredyepm23** [Wiseonesoft/cordova-whatsapp-sticker-plugin#4]
I have an assignment from the school I tried but have not succeeded, can I see the ionic source code 3 ,thank you sir.

**Comment by fredyepm23** [comment]
> I have an assignment from the school I tried but have not succeeded, can I see the ionic source code 3 ,thank you sir.

**Comment by H4ad** [comment]
Which platform did you try? I removed the last source code because it contains some sensitive information, but I want to create another to leave as an example.

When you tried to use, what errors happen?

**Comment by H4ad** [comment]
@fredyepm23 I created a PR to add a project working with plugin, i tested with Android and no errors occurred, after the 6th of this month, i finish the tests on Ios.

Please clone this repository, checkout to feature / example branch and try to run a build. If any errors occur, comment here and i will try to help you.

**Comment by fredyepm23** [comment]
I use ionic 3  for android ,not ios

**Comment by H4ad** [comment]
@fredyepm23 Okay, the example with ios i didn't test yet, but with android i already tested it. 

Did you try to run the example?

**Comment by H4ad** [comment]
@fredyepm23 i added installation guides in [README.md](https://github.com/H4ad/cordova-whatsapp-sticker-plugin/blob/feature/example/example/README.md) inside folder example.
